id: db37ce43ef2943b587fd1839a8379276
initial_creation_type: ocr
source_metadata:
  volumes:
    d94ed0f0e0fe4ab4bf8b474a5bba4945:
      base_file: v075.txt
      image_group_id: I1PD95921
      title: ''
      total_pages: 1774
      volume_number: 76
